version: '3.8'

services:
  postgres-master:
    build: ./master
    container_name: postgres-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-master-data:/var/lib/postgresql/data
      - ./master/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./master/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    networks:
      - postgres-net
    restart: unless-stopped

  postgres-slave:
    build: ./slave
    container_name: postgres-slave
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    depends_on:
      - postgres-master
    volumes:
      - pg-slave-data:/var/lib/postgresql/data
    networks:
      - postgres-net
    restart: unless-stopped

volumes:
  pg-master-data:
  pg-slave-data:

networks:
  postgres-net:
    driver: bridge
